apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-home-ui-deployment
  labels:
    app: zevrant-home-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zevrant-home-ui
  template:
    metadata:
      labels:
        app: zevrant-home-ui
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        architecture: amd64
      containers:
        - name: zevrant-home-ui
          image: zevrant/zevrant-home-ui:16.0.21
          env:
            - name: ENVIRONMENT
              value: develop
            - name: PROXY_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: proxy-creds
                  key: proxyCreds
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
