apiVersion: apps/v1
kind: Deployment
metadata:
  name: zevrant-home-ui-deployment
  labels:
    app: zevrant-home-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zevrant-home-ui
  template:
    metadata:
      labels:
        app: zevrant-home-ui
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        architecture: amd64
      containers:
        - name: zevrant-home-ui
          image: zevrant/zevrant-home-ui:$VERSION
          env:
            - name: ENVIRONMENT
              value: $ENVIRONMENT
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: zevrant-home-ui-aws
                  key: username
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: zevrant-home-ui-aws
                  key: password
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
          resources:
            requests:
              memory: 1Gi
              cpu: 100m
            limits:
              memory: 4Gi
              cpu: 500m
