server:
  ssl:
    key-store: /usr/local/microservices/zevrant-home-services/zevrant-home-ui/zevrant-services.p12
    key-store-type: PKCS12
    key-store-password: ${password}
    key-alias: 1
    enabled: true

zevrant:
  services:
    keycloak:
      baseUrl: https://zevrant-services.com

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1200000
      routes:
        - id: model
          uri: https://zevrant-model-service
          predicates:
            - Path=/zevrant-model-service/**
        - id: oauth
          uri: https://zevrant-oauth2-service
          predicates:
            - Path=/auth/**
        - id: oauth2
          uri: https://zevrant-keycloak-service
          predicates:
            - Path=/auth/realms/zevrant-services/**
        - id: outsource
          uri: https://zevrant-outsource-service
          predicates:
            - Path=/zevrant-outsource-service/**
        - id: backup
          uri: https://zevrant-backup-service
          predicates:
            - Path=/zevrant-backup-service/**
        - id: acra
          uri: https://zevrant-acra-backend
          predicates:
            - Path=/zevrant-acra-backend/**
        - id: notifications
          uri: https://zevrant-notification-service
          predicates:
            - Path=/zevrant-notification-service/**
        - id: kafka-proxy
          uri: wss://zevrant-kafka-proxy
          predicates:
            - Path=/socket.io
